name: connectivity
channels:
  - conda-forge
dependencies:
  - python=3.9*
  - pyproj<3
  - geopandas
  - osmnx
  - pandana
  - psycopg2
  - geoalchemy2
  - matplotlib
  - openpyxl
  - sqlalchemy
  - sqlalchemy-utils
  - black
  - flake8
  - jupyterlab
  - numpy ==1.22.4
  - folium
  - python-dotenv
  - networkx
  - tqdm
  - pip
  - pip:
      - git+https://github.com/mmorley0395/pg-data-etl
      - git+https://github.com/dvrpc/network-routing.git
